development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: micro_notes_development
  username: dbuser
  password: db.password
  pool: 5
test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: micro_notes_test
  username: dbuser
  password: db.password
  pool: 5
production:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: micro_notes
  username: dbuser
  password: db.password
  pool: 5
